---
# Play 1: Proxmox VM Creation
- name: Create and Start Proxmox VM
  hosts: build  # REQUIRES VALID INVENTORY GROUP
  collections:
    - community.general  # MUST BE INSTALLED IN EXECUTION ENVIRONMENT
  vars:
    proxmox_node: proxmox
    proxmox_api_host: 10.0.0.200
    proxmox_api_port: 8006
    validate_certs: no  # For self-signed certificates

  tasks:
    - name: Clone VM template
      community.general.proxmox_kvm:
        validate_certs: no
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"  # FROM AWX CREDENTIALS
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        validate_certs: "{{ validate_certs }}"
        storage: local
        clone: test-vm-1
        name: "{{ vm_name }}"
        full: true
      register: vm_creation

    - name: Wait for clone completion
      ansible.builtin.pause:
        seconds: 10
      when: vm_creation.changed

    - name: Start cloned VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        name: "{{ vm_name }}"
        state: started

# Play 2: Configure new VM
- name: Configure VM Network
  hosts: new_vm  # DYNAMIC INVENTORY REQUIRED
  become: yes
  tasks:
    - name: Set static IP
      ansible.builtin.lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-ens18"
        regexp: "^IPADDR="
        line: "IPADDR={{ new_IP }}"
        backup: yes

    - name: Reboot VM
      ansible.builtin.reboot:
        reboot_timeout: 600
