---
# Play 1: Proxmox VM Creation with Debugging
- name: Create and Start Proxmox VM
  hosts: build
  collections:
    - community.general
  vars:
    proxmox_node: proxmox
    proxmox_api_host: 10.0.0.200
    proxmox_api_port: 8006
    validate_certs: no

  tasks:
    # Debugging: Show input variables
    - name: Display VM creation parameters
      ansible.builtin.debug:
        msg: |
          VM Name: {{ vm_name }}
          Proxmox Host: {{ proxmox_api_host }}:{{ proxmox_api_port }}
          Clone Template: test-vm-1

    # Debugging: Verify API connection
    - name: Test Proxmox API connection
      ansible.builtin.uri:
        url: "https://{{ proxmox_api_host }}:{{ proxmox_api_port }}/api2/json"
        validate_certs: no
        status_code: 200
      register: api_test
      ignore_errors: yes

    - name: Show API connection result
      ansible.builtin.debug:
        var: api_test

    # Main VM creation task
    - name: Clone VM template
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        validate_certs: "{{ validate_certs }}"
        storage: local
        clone: test-vm-1
        name: "{{ vm_name }}"
        full: true
      register: vm_creation
      retries: 3
      delay: 10
      until: vm_creation is succeeded

    - name: Display VM creation results
      ansible.builtin.debug:
        var: vm_creation

    - name: Wait for clone completion
      ansible.builtin.pause:
        seconds: 10
      when: vm_creation.changed

    - name: Start cloned VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        name: "{{ vm_name }}"
        state: started
      register: vm_start

    - name: Display VM start resu
