---
- name: Create and Configure Proxmox VM
  hosts: build
  collections:
    - community.general  # Required for proxmox_kvm module
  vars:
    proxmox_node: proxmox
    proxmox_api_host: 10.0.0.200
    proxmox_api_port: 8006

  tasks:
    - name: Clone VM template
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        validate_certs: no  # Add if using self-signed certs
        storage: local
        clone: test-vm-1
        name: "{{ vm_name }}"
        full: true
      register: vm_creation

    - name: Wait for clone completion
      ansible.builtin.pause:
        seconds: 10
      when: vm_creation.changed

    - name: Start cloned VM
      community.general.proxmox_kvm:
        node: "{{ proxmox_node }}"
        api_user: "root@pam"
        api_password: "{{ proxmox_pass }}"
        api_host: "{{ proxmox_api_host }}"
        api_port: "{{ proxmox_api_port }}"
        name: "{{ vm_name }}"
        state: started

    - name: Wait for VM initialization
      ansible.builtin.pause:
        seconds: 20

- name: Configure new VM
  hosts: "{{ vm_name }}"  # Dynamic host targeting
  become: yes
  vars:
    network_interface: ens18  # Verify interface name

  tasks:
    - name: Configure static IP
      ansible.builtin.lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{ network_interface }}"
        regexp: "^IPADDR="
        line: "IPADDR={{ new_IP }}"
        backup: yes

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}.securedevguy.local"

    - name: Reboot VM
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Wait for system to come back
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
